name: "Search for rpi4s"

on:
  push:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cool-components:
    name: "Cool Components"
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://coolcomponents.co.uk/collections/raspberry-pi-boards/products/raspberry-pi-4?variant=32889923633213" | grep "Sold out"

  pimoroni:
    name: "Pimoroni"
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://shop.pimoroni.com/products/raspberry-pi-4?variant=31856486416467" | grep "Out of stock"

  rapid:
    name: "Rapid"
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://www.rapidonline.com/raspberry-pi-4-model-b-8gb-75-1013" | grep "schema.org/OutOfStock"

  sb-components:
    name: "SB Components"
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://shop.sb-components.co.uk/products/raspberry-pi-4-model-b?variant=39802032816211" | grep "Sold Out"

  the-pihut:
    name: "The PiHut"
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://thepihut.com/products/raspberry-pi-4-model-b?variant=31994565689406" | grep "Sold out"
