name: "SB Components"

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for 'Sold Out'
        run: |
          curl "https://shop.sb-components.co.uk/products/raspberry-pi-4-model-b?variant=39802032816211" | grep "Sold Out"
